services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    container_name: backend
    image: backend:latest
    env_file: .env
    build:
      context: ./designer-back
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      ConnectionStrings__Default: >
        Host=${POSTGRES_HOST};
        Port=${POSTGRES_PORT};
        Database=esp32-server;
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/Data/Seed:/app/Data/Seed
  
  frontend:
    container_name: frontend
    build:
      context: ./designer-front
    depends_on:
      backend:
        condition: service_started
      mongo:
        condition: service_started
    environment:
      BACKEND_API: ${BACKEND_API}
    ports:
      - "3000:3000"
  
  cloudflare:
    container_name: cloudflare
    build:
      context: ./designer-cloudflare

volumes:
  pgdata:
  mongodata:
